name: CI/CD Pipeline

env:
  DOTNET_VERSION: '8.0.300'
  SOLUTION_PATH: './KafkaProducerSample.sln'
  GITHUB_FEED_URL: 'https://nuget.pkg.github.com/prafaelmsantos/index.json'
  GITHUB_USERNAME: 'prafaelmsantos'
  GITHUB_PASSWORD: ${{ secrets.TOKEN }}
  
on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Add GitHub Packages as a NuGet source
      run: |
        dotnet nuget add source ${{ env.GITHUB_FEED_URL }} \
          --name github \
          --username ${{ env.GITHUB_USERNAME }} \
          --password ${{ env.GITHUB_PASSWORD }} \
          --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build the project
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --verbosity normal